//! The [`Controller`] trait and the internal, type-erased controller registry.

use crate::openapi::PathItem;
use crate::schema::Components;
use std::any::Any;
use std::sync::Arc;

/// Implemented by controllers (via `#[controller]`).
///
/// Exposes the OpenAPI paths and components contributed by the controller.
pub trait Controller: Send + Sync + 'static {
    /// The `(path, path item)` pairs and schemas contributed by this controller.
    fn openapi(&self) -> (Vec<(String, PathItem)>, Components);
}

/// Internal trait generated by `#[controller]` that builds the axum router.
#[doc(hidden)]
pub trait __Router: Controller {
    fn __router(self: Arc<Self>) -> axum::Router;
}

/// Type-erased controller openapi extractor.
type ControllerOpenApi = fn(&(dyn Any + Send + Sync)) -> (Vec<(String, PathItem)>, Components);

/// A type-erased controller that can build both its routes and its OpenAPI
/// contribution without requiring `Clone`.
pub(crate) struct ControllerBox {
    inner: Arc<dyn Any + Send + Sync>,
    build: fn(Arc<dyn Any + Send + Sync>) -> axum::Router,
    openapi: ControllerOpenApi,
}

impl ControllerBox {
    pub(crate) fn new<C: __Router>(c: C) -> Self {
        let inner: Arc<C> = Arc::new(c);
        let build = |any: Arc<dyn Any + Send + Sync>| {
            let controller: Arc<C> = any
                .downcast::<C>()
                .expect("velton: internal controller type mismatch");
            controller.__router()
        };
        let openapi = |any: &(dyn Any + Send + Sync)| {
            let controller: &C = any
                .downcast_ref::<C>()
                .expect("velton: internal controller type mismatch");
            controller.openapi()
        };
        Self {
            inner,
            build,
            openapi,
        }
    }

    pub(crate) fn build_router(&self) -> axum::Router {
        (self.build)(Arc::clone(&self.inner))
    }

    pub(crate) fn openapi(&self) -> (Vec<(String, PathItem)>, Components) {
        (self.openapi)(self.inner.as_ref())
    }
}
